-- =====================================================
-- TEA APP - SUPER ADMIN PANEL SCHEMA
-- =====================================================
-- This schema adds tables for admin functionality:
-- 1. Admin users with roles
-- 2. Reports system for flagged content
-- 3. Moderation actions log
-- 4. Analytics tracking
-- 5. Kettle suggestions/requests
-- 6. Rate limiting tracking
-- =====================================================

-- =====================================================
-- ADMIN USERS TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS admin_users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT UNIQUE NOT NULL,
      password_hash TEXT NOT NULL,
        name TEXT NOT NULL,
          role TEXT NOT NULL DEFAULT 'moderator' CHECK (role IN ('super_admin', 'admin', 'moderator')),
            is_active BOOLEAN DEFAULT true,
              last_login TIMESTAMPTZ,
                created_at TIMESTAMPTZ DEFAULT now(),
                  updated_at TIMESTAMPTZ DEFAULT now()
                  );

                  -- Create index for email lookups
                  CREATE INDEX IF NOT EXISTS idx_admin_users_email ON admin_users(email);

                  -- =====================================================
                  -- REPORTS TABLE - For flagged/reported content
                  -- =====================================================
                  CREATE TABLE IF NOT EXISTS reports (
                    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                      post_id UUID REFERENCES posts(id) ON DELETE CASCADE,
                        reporter_fingerprint TEXT, -- Anonymous reporter identifier
                          reason TEXT NOT NULL CHECK (reason IN (
                              'spam', 
                                  'harassment', 
                                      'hate_speech', 
                                          'explicit_content', 
                                              'misinformation', 
                                                  'doxxing',
                                                      'self_harm',
                                                          'other'
                                                            )),
                                                              description TEXT, -- Additional details from reporter
                                                                status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'reviewed', 'actioned', 'dismissed')),
                                                                  reviewed_by UUID REFERENCES admin_users(id),
                                                                    reviewed_at TIMESTAMPTZ,
                                                                      action_taken TEXT, -- What action was taken
                                                                        created_at TIMESTAMPTZ DEFAULT now()
                                                                        );

                                                                        -- Create indexes for reports
                                                                        CREATE INDEX IF NOT EXISTS idx_reports_status ON reports(status);
                                                                        CREATE INDEX IF NOT EXISTS idx_reports_post_id ON reports(post_id);
                                                                        CREATE INDEX IF NOT EXISTS idx_reports_created_at ON reports(created_at DESC);

                                                                        -- =====================================================
                                                                        -- MODERATION ACTIONS LOG
                                                                        -- =====================================================
                                                                        CREATE TABLE IF NOT EXISTS moderation_log (
                                                                          id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                                                                            admin_id UUID REFERENCES admin_users(id),
                                                                              action_type TEXT NOT NULL CHECK (action_type IN (
                                                                                  'delete_post',
                                                                                      'hide_post',
                                                                                          'restore_post',
                                                                                              'ban_fingerprint',
                                                                                                  'unban_fingerprint',
                                                                                                      'approve_kettle',
                                                                                                          'reject_kettle',
                                                                                                              'edit_kettle',
                                                                                                                  'delete_kettle',
                                                                                                                      'dismiss_report',
                                                                                                                          'action_report'
                                                                                                                            )),
                                                                                                                              target_type TEXT NOT NULL CHECK (target_type IN ('post', 'kettle', 'report', 'user')),
                                                                                                                                target_id UUID NOT NULL,
                                                                                                                                  details JSONB, -- Additional action details
                                                                                                                                    created_at TIMESTAMPTZ DEFAULT now()
                                                                                                                                    );

                                                                                                                                    -- Create indexes for moderation log
                                                                                                                                    CREATE INDEX IF NOT EXISTS idx_moderation_log_admin ON moderation_log(admin_id);
                                                                                                                                    CREATE INDEX IF NOT EXISTS idx_moderation_log_target ON moderation_log(target_type, target_id);
                                                                                                                                    CREATE INDEX IF NOT EXISTS idx_moderation_log_created_at ON moderation_log(created_at DESC);

                                                                                                                                    -- =====================================================
                                                                                                                                    -- BANNED FINGERPRINTS - For blocking repeat offenders
                                                                                                                                    -- =====================================================
                                                                                                                                    CREATE TABLE IF NOT EXISTS banned_fingerprints (
                                                                                                                                      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                                                                                                                                        fingerprint TEXT UNIQUE NOT NULL,
                                                                                                                                          reason TEXT,
                                                                                                                                            banned_by UUID REFERENCES admin_users(id),
                                                                                                                                              expires_at TIMESTAMPTZ, -- NULL means permanent
                                                                                                                                                created_at TIMESTAMPTZ DEFAULT now()
                                                                                                                                                );

                                                                                                                                                CREATE INDEX IF NOT EXISTS idx_banned_fingerprints_fp ON banned_fingerprints(fingerprint);

                                                                                                                                                -- =====================================================
                                                                                                                                                -- KETTLE SUGGESTIONS - User-submitted kettle ideas
                                                                                                                                                -- =====================================================
                                                                                                                                                CREATE TABLE IF NOT EXISTS kettle_suggestions (
                                                                                                                                                  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                                                                                                                                                    name TEXT NOT NULL,
                                                                                                                                                      slug TEXT NOT NULL,
                                                                                                                                                        description TEXT,
                                                                                                                                                          icon TEXT DEFAULT '🍵',
                                                                                                                                                            suggested_by_fingerprint TEXT,
                                                                                                                                                              status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
                                                                                                                                                                reviewed_by UUID REFERENCES admin_users(id),
                                                                                                                                                                  reviewed_at TIMESTAMPTZ,
                                                                                                                                                                    rejection_reason TEXT,
                                                                                                                                                                      created_at TIMESTAMPTZ DEFAULT now()
                                                                                                                                                                      );

                                                                                                                                                                      CREATE INDEX IF NOT EXISTS idx_kettle_suggestions_status ON kettle_suggestions(status);

                                                                                                                                                                      -- =====================================================
                                                                                                                                                                      -- ANALYTICS - Track post views and engagement
                                                                                                                                                                      -- =====================================================
                                                                                                                                                                      CREATE TABLE IF NOT EXISTS post_views (
                                                                                                                                                                        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                                                                                                                                                                          post_id UUID REFERENCES posts(id) ON DELETE CASCADE,
                                                                                                                                                                            viewer_fingerprint TEXT,
                                                                                                                                                                              created_at TIMESTAMPTZ DEFAULT now()
                                                                                                                                                                              );

                                                                                                                                                                              -- Create indexes for analytics
                                                                                                                                                                              CREATE INDEX IF NOT EXISTS idx_post_views_post_id ON post_views(post_id);
                                                                                                                                                                              CREATE INDEX IF NOT EXISTS idx_post_views_created_at ON post_views(created_at);

                                                                                                                                                                              -- Aggregate view count (materialized for performance)
                                                                                                                                                                              CREATE MATERIALIZED VIEW IF NOT EXISTS post_view_counts AS
                                                                                                                                                                              SELECT 
                                                                                                                                                                                post_id,
                                                                                                                                                                                  COUNT(*) as view_count,
                                                                                                                                                                                    COUNT(DISTINCT viewer_fingerprint) as unique_views
                                                                                                                                                                                    FROM post_views
                                                                                                                                                                                    GROUP BY post_id;

                                                                                                                                                                                    CREATE UNIQUE INDEX IF NOT EXISTS idx_post_view_counts_post_id ON post_view_counts(post_id);

                                                                                                                                                                                    -- =====================================================
                                                                                                                                                                                    -- RATE LIMITING - Track user actions for spam prevention
                                                                                                                                                                                    -- =====================================================
                                                                                                                                                                                    CREATE TABLE IF NOT EXISTS rate_limit_log (
                                                                                                                                                                                      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                                                                                                                                                                                        fingerprint TEXT NOT NULL,
                                                                                                                                                                                          action_type TEXT NOT NULL CHECK (action_type IN ('post', 'reply', 'vote', 'report')),
                                                                                                                                                                                            created_at TIMESTAMPTZ DEFAULT now()
                                                                                                                                                                                            );

                                                                                                                                                                                            -- Create indexes for rate limiting
                                                                                                                                                                                            CREATE INDEX IF NOT EXISTS idx_rate_limit_fingerprint ON rate_limit_log(fingerprint, action_type);
                                                                                                                                                                                            CREATE INDEX IF NOT EXISTS idx_rate_limit_created_at ON rate_limit_log(created_at);

                                                                                                                                                                                            -- =====================================================
                                                                                                                                                                                            -- PROFANITY FILTER WORDS
                                                                                                                                                                                            -- =====================================================
                                                                                                                                                                                            CREATE TABLE IF NOT EXISTS blocked_words (
                                                                                                                                                                                              id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                                                                                                                                                                                                word TEXT UNIQUE NOT NULL,
                                                                                                                                                                                                  severity TEXT DEFAULT 'medium' CHECK (severity IN ('low', 'medium', 'high')),
                                                                                                                                                                                                    created_at TIMESTAMPTZ DEFAULT now()
                                                                                                                                                                                                    );

                                                                                                                                                                                                    -- =====================================================
                                                                                                                                                                                                    -- USER PREFERENCES - For anonymous users
                                                                                                                                                                                                    -- =====================================================
                                                                                                                                                                                                    CREATE TABLE IF NOT EXISTS user_preferences (
                                                                                                                                                                                                      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                                                                                                                                                                                                        fingerprint TEXT UNIQUE NOT NULL,
                                                                                                                                                                                                          theme TEXT DEFAULT 'dark' CHECK (theme IN ('dark', 'light', 'system')),
                                                                                                                                                                                                            favorite_kettles UUID[] DEFAULT '{}',
                                                                                                                                                                                                              notification_enabled BOOLEAN DEFAULT false,
                                                                                                                                                                                                                created_at TIMESTAMPTZ DEFAULT now(),
                                                                                                                                                                                                                  updated_at TIMESTAMPTZ DEFAULT now()
                                                                                                                                                                                                                  );

                                                                                                                                                                                                                  CREATE INDEX IF NOT EXISTS idx_user_preferences_fp ON user_preferences(fingerprint);

                                                                                                                                                                                                                  -- =====================================================
                                                                                                                                                                                                                  -- HELPER FUNCTIONS
                                                                                                                                                                                                                  -- =====================================================

                                                                                                                                                                                                                  -- Function to check if a fingerprint is banned
                                                                                                                                                                                                                  CREATE OR REPLACE FUNCTION is_fingerprint_banned(fp TEXT)
                                                                                                                                                                                                                  RETURNS BOOLEAN AS $$
                                                                                                                                                                                                                  BEGIN
                                                                                                                                                                                                                    RETURN EXISTS (
                                                                                                                                                                                                                        SELECT 1 FROM banned_fingerprints 
                                                                                                                                                                                                                            WHERE fingerprint = fp 
                                                                                                                                                                                                                                AND (expires_at IS NULL OR expires_at > now())
                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                  END;
                                                                                                                                                                                                                                  $$ LANGUAGE plpgsql;

                                                                                                                                                                                                                                  -- Function to check rate limit (returns true if within limit)
                                                                                                                                                                                                                                  CREATE OR REPLACE FUNCTION check_rate_limit(
                                                                                                                                                                                                                                    fp TEXT, 
                                                                                                                                                                                                                                      action TEXT, 
                                                                                                                                                                                                                                        max_count INT, 
                                                                                                                                                                                                                                          window_minutes INT
                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                          RETURNS BOOLEAN AS $$
                                                                                                                                                                                                                                          DECLARE
                                                                                                                                                                                                                                            action_count INT;
                                                                                                                                                                                                                                            BEGIN
                                                                                                                                                                                                                                              SELECT COUNT(*) INTO action_count
                                                                                                                                                                                                                                                FROM rate_limit_log
                                                                                                                                                                                                                                                  WHERE fingerprint = fp 
                                                                                                                                                                                                                                                      AND action_type = action
                                                                                                                                                                                                                                                          AND created_at > now() - (window_minutes || ' minutes')::INTERVAL;
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                              RETURN action_count < max_count;
                                                                                                                                                                                                                                                              END;
                                                                                                                                                                                                                                                              $$ LANGUAGE plpgsql;

                                                                                                                                                                                                                                                              -- Function to log rate limit action
                                                                                                                                                                                                                                                              CREATE OR REPLACE FUNCTION log_rate_limit(fp TEXT, action TEXT)
                                                                                                                                                                                                                                                              RETURNS VOID AS $$
                                                                                                                                                                                                                                                              BEGIN
                                                                                                                                                                                                                                                                INSERT INTO rate_limit_log (fingerprint, action_type)
                                                                                                                                                                                                                                                                  VALUES (fp, action);
                                                                                                                                                                                                                                                                  END;
                                                                                                                                                                                                                                                                  $$ LANGUAGE plpgsql;

                                                                                                                                                                                                                                                                  -- Function to get trending posts (heat + recency algorithm)
                                                                                                                                                                                                                                                                  CREATE OR REPLACE FUNCTION get_trending_posts(
                                                                                                                                                                                                                                                                    time_window_hours INT DEFAULT 24,
                                                                                                                                                                                                                                                                      limit_count INT DEFAULT 20
                                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                                      RETURNS TABLE (
                                                                                                                                                                                                                                                                        id UUID,
                                                                                                                                                                                                                                                                          content TEXT,
                                                                                                                                                                                                                                                                            heat_score INT,
                                                                                                                                                                                                                                                                              anonymous_identity TEXT,
                                                                                                                                                                                                                                                                                created_at TIMESTAMPTZ,
                                                                                                                                                                                                                                                                                  kettle_id UUID,
                                                                                                                                                                                                                                                                                    kettle_name TEXT,
                                                                                                                                                                                                                                                                                      kettle_slug TEXT,
                                                                                                                                                                                                                                                                                        trending_score FLOAT
                                                                                                                                                                                                                                                                                        ) AS $$
                                                                                                                                                                                                                                                                                        BEGIN
                                                                                                                                                                                                                                                                                          RETURN QUERY
                                                                                                                                                                                                                                                                                            SELECT 
                                                                                                                                                                                                                                                                                                p.id,
                                                                                                                                                                                                                                                                                                    p.content,
                                                                                                                                                                                                                                                                                                        p.heat_score,
                                                                                                                                                                                                                                                                                                            p.anonymous_identity,
                                                                                                                                                                                                                                                                                                                p.created_at,
                                                                                                                                                                                                                                                                                                                    p.kettle_id,
                                                                                                                                                                                                                                                                                                                        k.name as kettle_name,
                                                                                                                                                                                                                                                                                                                            k.slug as kettle_slug,
                                                                                                                                                                                                                                                                                                                                -- Trending score: heat * recency factor (exponential decay)
                                                                                                                                                                                                                                                                                                                                    (COALESCE(p.heat_score, 0) * EXP(-EXTRACT(EPOCH FROM (now() - p.created_at)) / (time_window_hours * 3600)))::FLOAT as trending_score
                                                                                                                                                                                                                                                                                                                                      FROM posts p
                                                                                                                                                                                                                                                                                                                                        JOIN kettles k ON p.kettle_id = k.id
                                                                                                                                                                                                                                                                                                                                          WHERE p.parent_post_id IS NULL
                                                                                                                                                                                                                                                                                                                                              AND p.created_at > now() - (time_window_hours || ' hours')::INTERVAL
                                                                                                                                                                                                                                                                                                                                                  AND NOT p.is_hidden
                                                                                                                                                                                                                                                                                                                                                    ORDER BY trending_score DESC
                                                                                                                                                                                                                                                                                                                                                      LIMIT limit_count;
                                                                                                                                                                                                                                                                                                                                                      END;
                                                                                                                                                                                                                                                                                                                                                      $$ LANGUAGE plpgsql;

                                                                                                                                                                                                                                                                                                                                                      -- =====================================================
                                                                                                                                                                                                                                                                                                                                                      -- ADD MISSING COLUMNS TO POSTS TABLE
                                                                                                                                                                                                                                                                                                                                                      -- =====================================================
                                                                                                                                                                                                                                                                                                                                                      DO $$ 
                                                                                                                                                                                                                                                                                                                                                      BEGIN
                                                                                                                                                                                                                                                                                                                                                        -- Add is_hidden column if it doesn't exist
                                                                                                                                                                                                                                                                                                                                                          IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'posts' AND column_name = 'is_hidden') THEN
                                                                                                                                                                                                                                                                                                                                                              ALTER TABLE posts ADD COLUMN is_hidden BOOLEAN DEFAULT false;
                                                                                                                                                                                                                                                                                                                                                                END IF;
                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                    -- Add report_count column for quick access
                                                                                                                                                                                                                                                                                                                                                                      IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'posts' AND column_name = 'report_count') THEN
                                                                                                                                                                                                                                                                                                                                                                          ALTER TABLE posts ADD COLUMN report_count INT DEFAULT 0;
                                                                                                                                                                                                                                                                                                                                                                            END IF;
                                                                                                                                                                                                                                                                                                                                                                            END $$;

                                                                                                                                                                                                                                                                                                                                                                            -- =====================================================
                                                                                                                                                                                                                                                                                                                                                                            -- RLS POLICIES FOR ADMIN TABLES
                                                                                                                                                                                                                                                                                                                                                                            -- =====================================================

                                                                                                                                                                                                                                                                                                                                                                            -- Reports: Anyone can insert, only admins can read/update
                                                                                                                                                                                                                                                                                                                                                                            ALTER TABLE reports ENABLE ROW LEVEL SECURITY;

                                                                                                                                                                                                                                                                                                                                                                            CREATE POLICY "Anyone can report posts"
                                                                                                                                                                                                                                                                                                                                                                              ON reports FOR INSERT
                                                                                                                                                                                                                                                                                                                                                                                TO anon, authenticated
                                                                                                                                                                                                                                                                                                                                                                                  WITH CHECK (true);

                                                                                                                                                                                                                                                                                                                                                                                  -- Rate limit log: Service can insert
                                                                                                                                                                                                                                                                                                                                                                                  ALTER TABLE rate_limit_log ENABLE ROW LEVEL SECURITY;

                                                                                                                                                                                                                                                                                                                                                                                  CREATE POLICY "Service can insert rate limits"
                                                                                                                                                                                                                                                                                                                                                                                    ON rate_limit_log FOR INSERT
                                                                                                                                                                                                                                                                                                                                                                                      TO anon, authenticated
                                                                                                                                                                                                                                                                                                                                                                                        WITH CHECK (true);

                                                                                                                                                                                                                                                                                                                                                                                        -- User preferences: Users can manage their own preferences
                                                                                                                                                                                                                                                                                                                                                                                        ALTER TABLE user_preferences ENABLE ROW LEVEL SECURITY;

                                                                                                                                                                                                                                                                                                                                                                                        CREATE POLICY "Users can manage own preferences"
                                                                                                                                                                                                                                                                                                                                                                                          ON user_preferences FOR ALL
                                                                                                                                                                                                                                                                                                                                                                                            TO anon, authenticated
                                                                                                                                                                                                                                                                                                                                                                                              USING (true)
                                                                                                                                                                                                                                                                                                                                                                                                WITH CHECK (true);

                                                                                                                                                                                                                                                                                                                                                                                                -- =====================================================
                                                                                                                                                                                                                                                                                                                                                                                                -- REFRESH MATERIALIZED VIEW FUNCTION
                                                                                                                                                                                                                                                                                                                                                                                                -- =====================================================
                                                                                                                                                                                                                                                                                                                                                                                                CREATE OR REPLACE FUNCTION refresh_post_view_counts()
                                                                                                                                                                                                                                                                                                                                                                                                RETURNS VOID AS $$
                                                                                                                                                                                                                                                                                                                                                                                                BEGIN
                                                                                                                                                                                                                                                                                                                                                                                                  REFRESH MATERIALIZED VIEW CONCURRENTLY post_view_counts;
                                                                                                                                                                                                                                                                                                                                                                                                  END;
                                                                                                                                                                                                                                                                                                                                                                                                  $$ LANGUAGE plpgsql;

                                                                                                                                                                                                                                                                                                                                                                                                  -- =====================================================
                                                                                                                                                                                                                                                                                                                                                                                                  -- DAILY/WEEKLY LEADERBOARD VIEW
                                                                                                                                                                                                                                                                                                                                                                                                  -- =====================================================
                                                                                                                                                                                                                                                                                                                                                                                                  CREATE OR REPLACE VIEW daily_leaderboard AS
                                                                                                                                                                                                                                                                                                                                                                                                  SELECT 
                                                                                                                                                                                                                                                                                                                                                                                                    p.id,
                                                                                                                                                                                                                                                                                                                                                                                                      p.content,
                                                                                                                                                                                                                                                                                                                                                                                                        p.heat_score,
                                                                                                                                                                                                                                                                                                                                                                                                          p.anonymous_identity,
                                                                                                                                                                                                                                                                                                                                                                                                            p.created_at,
                                                                                                                                                                                                                                                                                                                                                                                                              k.name as kettle_name,
                                                                                                                                                                                                                                                                                                                                                                                                                k.slug as kettle_slug
                                                                                                                                                                                                                                                                                                                                                                                                                FROM posts p
                                                                                                                                                                                                                                                                                                                                                                                                                JOIN kettles k ON p.kettle_id = k.id
                                                                                                                                                                                                                                                                                                                                                                                                                WHERE p.parent_post_id IS NULL
                                                                                                                                                                                                                                                                                                                                                                                                                  AND p.created_at > now() - INTERVAL '24 hours'
                                                                                                                                                                                                                                                                                                                                                                                                                    AND NOT COALESCE(p.is_hidden, false)
                                                                                                                                                                                                                                                                                                                                                                                                                    ORDER BY p.heat_score DESC
                                                                                                                                                                                                                                                                                                                                                                                                                    LIMIT 50;

                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE OR REPLACE VIEW weekly_leaderboard AS
                                                                                                                                                                                                                                                                                                                                                                                                                    SELECT 
                                                                                                                                                                                                                                                                                                                                                                                                                      p.id,
                                                                                                                                                                                                                                                                                                                                                                                                                        p.content,
                                                                                                                                                                                                                                                                                                                                                                                                                          p.heat_score,
                                                                                                                                                                                                                                                                                                                                                                                                                            p.anonymous_identity,
                                                                                                                                                                                                                                                                                                                                                                                                                              p.created_at,
                                                                                                                                                                                                                                                                                                                                                                                                                                k.name as kettle_name,
                                                                                                                                                                                                                                                                                                                                                                                                                                  k.slug as kettle_slug
                                                                                                                                                                                                                                                                                                                                                                                                                                  FROM posts p
                                                                                                                                                                                                                                                                                                                                                                                                                                  JOIN kettles k ON p.kettle_id = k.id
                                                                                                                                                                                                                                                                                                                                                                                                                                  WHERE p.parent_post_id IS NULL
                                                                                                                                                                                                                                                                                                                                                                                                                                    AND p.created_at > now() - INTERVAL '7 days'
                                                                                                                                                                                                                                                                                                                                                                                                                                      AND NOT COALESCE(p.is_hidden, false)
                                                                                                                                                                                                                                                                                                                                                                                                                                      ORDER BY p.heat_score DESC
                                                                                                                                                                                                                                                                                                                                                                                                                                      LIMIT 100;
                                                                                                                                                                                                                                                                                                                                                                                                                                      